server:
  port: 8088
spring:
  application:
    name: bootcamp-priceservice
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:pricedb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    
  cloud:
    config:
      import-check:
        enabled: false
  sql:
      init:
        data-locations: classpath:db/data.sql
        schema-locations: classpath:db/schema.sql
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
